language: haskell
sudo: false
cache:
  directories:
  - $HOME/.stack/
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.3.1/stack-0.1.3.1-x86_64-linux.gz
  | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack
- stack --no-terminal setup
install:
- stack setup --no-terminal
- stack build --only-snapshot --no-terminal
script:
- stack test --pedantic --no-terminal
deploy:
  provider: hackage
  username: AlexanderThiemann
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: p7ZevKqxAu33Qm7NAioqjNzyS56yxpwPkg7apD5u9Uq2UmulweyrsTIEZwD3jDTKmkdfxNcmFKi+c8k3qNIAo8CO8mw3izLXGFpmA3tEh5CnV/eQMBtfq+AtP1ljGpCJRTjcaJ2/87/3SnD6qHsrpCo/1VprLEpG7OmF39XQ//KKdDj3YFsc9duNhcwCwRumYgI3fZAEgOXgqrfAxprKbIM+0IejgbpMoa/boXLrs8THcZp7FfFP/H9juEvCQugYg/om1OP1OGEKqMlFxV9i4WwhjVh+WheI5bznH3f8/fSUmdpPed/bnKWvy89NAMIhgpi5dvyGDJ4kGRwwCa3W7VMOFU353tayZV5nn0Taok7rRgrNcr1nMlupeM/6QkAp+mYGyYX/kFmBnoQCWhL2cEv05yX760oLuY3+PkG5wPUooT/ROdrpr6ZYSnozYFv3iOrnjj91UwVt91Fw1vL4aMjkjY1gn+oK0zCCLztyVLFNkWodJpmkxdcBE5jsn/n3FYrnyxIixxDh6oxyJl0jOPfHxeb+mqvtBhJRCqIb0OGyRlDCsLm5vmZhJuIQCtqbO3ciGeilSE64p0RDw6Hd75DiMxrbkh9akAJ/oHn247GqQ2Qqj40qxLyx1xeHFuOwkp/ncjuSIGcAo0HokJ//D423ZFdNxrFL1vtOlZVyOw8=
